-- Funções de string
SELECT LTRIM(' OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ ') AS RESULTADO;

SELECT TRIM(' OLÁ ') AS RESULTADO;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM','?') AS RESULTADO;

SELECT UPPER('olá, tudo bem?') AS RESULTADO;

SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM TABELA_DE_CLIENTES;

-- Funções de datas
-- Data atual
SELECT CURDATE();

-- Hora, minutos e segundos atual
SELECT CURRENT_TIME();

-- Data, hora, minutos e segundos atual
SELECT CURRENT_TIMESTAMP();

-- Ano atual
SELECT YEAR(CURRENT_TIMESTAMP());

-- Dia atual
SELECT DAY(CURRENT_TIMESTAMP());

-- Diferença entre datas
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2019-01-01') AS RESULTADO;

-- Aplicando Funções de datas na db de sucos_vendas
SELECT CURRENT_TIMESTAMP() AS DIA_HOJE , DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES , YEAR(DATA_VENDA) AS ANO FROM NOTAS_FISCAIS;

-- Funções matemáticas
SELECT (23+((25-2)/2)*45) AS RESULTADO;

SELECT CEILING(12.33333232323) AS RESULTADO;

SELECT ROUND(12.7777232323) AS RESULTADO;

SELECT FLOOR(12.7777232323) AS RESULTADO;

SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE * PRECO AS FATURAMENTO FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO FROM ITENS_NOTAS_FISCAIS;

-- Funções de conversão 
SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y - %U') ) AS RESULTADO;

SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;